admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

operator:
    resource: "@OperatorBundle/Resources/config/routing.yml"
    prefix:   /busoperator

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

register:
    resource: "@RegisterBundle/Resources/config/routing.yml"
    prefix:   /

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /login

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
